import React from 'react'
import { useNavigate } from 'react-router-dom';
import MainLayout from '../Layout/MainLayout';
import TextHeading from '../TextHeading/TextHeading';


const PlacesOfWorship = () => {
    const navigate = useNavigate()
    return (
        <MainLayout>
            <div className='history'>
                <TextHeading content='PLACES OF WORSHIP' />

                <article className="history_content">
                    <p>

                        CHAPEL OF CHRIST OUR LIGHT (PROTESTANT COMMUNITY)
                        The 1965  66 academic year of the University was officially scheduled to be the first session on the Main Campus at Akoka and to commence on Thursday, 23rd September, 1965, with the arrival of freshmen. Lectures were to begin on Monday, 4th October. Therefore, the Senior Deputy Registrar of the University, Mr. (now Rev.) Osinulu secured the approval of the University authorities for the temporary reservation of the ground floor of the University Library adjacent to the Administration Block as the place of worship for the protestant Christians on the Main Campus. A date (Sunday, 3rd October 1965) was fixed by the Bishop of Lagos, the Rt. Rev. S.I. Kale, for the dedication of the allotted place of worship.
                        The worship service of dedication was duly publicized among the campus community, staff and student and it took place as scheduled in the evening of that day, starting at 5pm. A brand new piano had been donated to the Chapel by the University authorities just before the dedication day. Very soon, a Chapel committee was elected and the time of normal Sunday worship services was fixed at 10:00am. The Committee firmly laid down a guideline for the nature of worship services to be held by the Chapel. The policy was that during University term (later altered to semester) the priests and the lay persons who would conduct the ten Oclock Sunday morning worship service should constitute a cross-section of the protestant church in Nigeria and there should be no bunching of preachers from a particular denomination for three or more consecutive Sundays. Instead there should be a lot of variation from Sunday to Sunday in the preachers denomination.
                        Whilst the University Library ground floor was the venue for Chapel services, the Sunday school classes for children were held in the lecture rooms of the then Faculty of Arts (now Faculty of Business Administration).
                        At the time this congregation started worshipping on the Main Campus, there was another protestant congregation holding Sunday worship services in the Hall of the Federal Advanced Teachers College which is now the Faculty of Education, University of Lagos
                        During the 1967  1968 academic year the committee of the two congregations appointed a joint sub-committee to pursue the desirable merger of both congregation, and to identify a suitable place of worship. The Hall of the College of Education was finally agreed upon as the unifying place of worship with effect from October 1968.
                        Mention must be made of the student group within the congregation. Christian Union and the Student Christian Movement have had branches within the University of Lagos protestant congregation since October, 1968.
                        The Joint Project
                        The first service of Carols and lessons jointly held by the Protestant Chapel with the Roman Catholics took place in December 1968 at the Central Concourse in front of the University Library entrance, since then it has been an annual event.
                        It was at the meeting of the Chapel Committee held 14th January, 1972, that a Chapel Building Committee was first appointed, but the Committee was not appointed till the start of the 1972  1973 session. Soon after it took off, the Committee held a meeting with representatives of the Roman Catholic congregation on the idea of a joint Chapel Building committee for Joint Chapel Building which would reflect the new ecumenical, thinking that would mean a great amount of savings for both congregations. The meeting unanimously favoured the idea and on 28th June, 1973 the launching of the Chapel of Christ our Light Appeal Fund took place in the Senior Common Room of the University. The name for the Chapel was decided by a poll taken among the two congregations on the various suggestions available and on the Joint Chapel Building Committees inspired opinion about the best name.
                        The University Authorities assistance with the Chapel Building project began in 1970. The Foundation stone of the Chapel Building was jointly laid by the Anglican and the Catholic Archbishop of Lagos, Rt Rev. Oluwole Segun and Archbishop Olubunmi Okogie respectively.
                        The journey has been a long one, but God remained faithful. With the financial support of the University and active fund raising of the Building Committee, there is now an edifice to the glory of God. The painting and permanent electrification were done in 1990/91 session. But with the wall and roof in place the two congregations began regular services in the Chapel in 1984. The Catholics hold Sunday morning service from 8:00am to 9:30am, and the Protestant from 10:00am to 11:30am.
                        A joint management Board of the Chapel of Christ our Light members of Catholic and Protestant congregation was officially inaugurated on the 28th March, 1991.
                        The task before the Board then included the completion of the physical structure landscaping and general beautification of the environment. The Board looked forward to a joint Christian graduation service, week of common prayer for all Christians, stimulating interest in religious activities on the Campus and educating the community in religious knowledge.
                        The Chapel of Christ our Light (Protestant) remains the Christian Community of the University of Lagos, for the non-Roman Catholic Christians. The Chapel of Christ our Light is the Headquarters of Heaven
                        ; and as a non-denominational Bible believing Congregation, we are a Kingdom minded people with passion for excellence in life, impacting the Community with the Gospel of Jesus Christ.
                        Two services hold on Sundays, with occasional joint services. The first service is 8:00am and the second service is 10:00am with workers meeting in between, at precisely 9:30am. Our midweek service; which is our Prayer meeting, holds every Wednesday at 6:00pm. The Holy Ghost Hour service holds every first day of the month at 6:00pm. These services are hybrid, meaning that you can attend physically or watch virtually. Night vigil holds every last Friday of the month at 11:00pm. We have Home Fellowship centers across the Campus and the City of Lagos, as displayed on our Website and on the Chapel App. The Chapel App can be downloaded from Play store or the IOS store. The list of ministries of the Chapel can also be found on the Chapel app and website. HYPERLINK "http://www.unilagchapel.org"www.unilagchapel.org
                        Membership of the Chapel cuts across every denomination. Come and find your place to worship and serve the Lord while passing through the University of Lagos, your life can never be the same again. We can also be found online on our digital platforms; Facebook, Instagram, Mixlr and on our Youtube channel.

                        History of St. Thomas more Catholic Chaplaincy, University of Lagos, Akoka, Nigeria
                        Development
                        The dream of having St. Thomas More Catholic Chaplaincy was first conceived in 1961 by the Apostolic Delegate to Nigeria - Archbishop Sergio Pignedoliand three English-speaking Jesuits in the persons of Frs. Paolo Dezza, Edward Rooney, and John McGinty, who were sent to the University of Lagos ahead of its opening in September 1962. The Christian worship began in 1963 when Rev. Fr. Joseph Schuyler and a few others held the first Sunday Mass in the Old Great hall of the now College of Medicine. The worship continued in the Old Great Hall till 1965 when it was moved to the Assembly hall of the Nursing School.
                        In 1966, when the University of Lagos moved to the permanent site in at Akoka, the  Catholic community began to meet at the Federal College of Education while those in the College of Medicine, Idi-Araba continued to meet there. St. Thomas More Catholic Chaplaincy started out in an ecumenical center called the Chapel of Christ our light. In November, 1967 the Catholic and Protestant communities, jointly instituted the planning for the Christian House of Worship on the University campus, and on the 1st of May, 1976, Archbishop Anthony Olubunmi Okogie (now Cardinal) and Bishop Segun of the Anglican diocese of Lagos jointly performed a fund raising ceremony and the laying of the foundation stone of Christ Our Light Chapel. The Catholic community in Akoka still continued to worship in the erstwhile College of Education until 1988, and by the 1st of March 1988 the chapel was sufficiently built for worship use.
                        This new beginning was with two Jesuit Priests, Frs. Joseph Schuyler and Joseph Schuh, who were also lecturers in the University of Lagos. Fr. Schuyler became the first Chaplain and co-Chairman of the Fund Raising and Building Committees of the Chapel of Christ our light (the University's Ecumenical Centre), which still stands today. In 1993, Fr John Jack Ryan took over as the Chaplain to the Catholic community in the Chapel of Christ our light. By 1999 Fr. Ryan handed over the running of the Chaplaincy to Rev. Fr. Francis Isichei (O.P.) who facilitated the building of a new Chapel, what is now known as St. Thomas More Catholic Chaplaincy.
                        The foundation Laying Ceremony was done by His Grace Anthony Olubunmi Okogie on the 26th of May, 2001, and on the 18th of April 2009, St. Thomas More Catholic Chapel was dedicated by His Eminence, Anthony Cardinal Olubunmi Okogie. Today we have a growing population of students, lecturers and Catholic faithful that leave in and around the University. Currently Rev. Fr. Paul Akin-Otiko, O.P. is the Chaplain, and is being assisted by Rev. Frs. Paulinus Onyenuru (OP) and Augustine Obiosa (OP).

                        Activities
                        There are two masses everyday: 6.30am and 6.00pm, on Saturdays there is only the morning mass at 6.30am. On Sundays, there are three masses: 6.30 am, 8.30am and 10.30am to keep the COVID-19 protocols.
                        The Chaplaincys Civic centre allows for the faith formation of the student community as well as the older members of the chaplaincy. The Chaplaincy, through her welfare organ, caters for confirmed indigent students and facilitates the meeting of the Nigerian Federation of Catholic Students.
                        The Chaplaincy runs like a-home-away-from-home for the students, the older members of the community help to support and counsel students who have issues to deal with.
                        The chaplaincy is precious to the Catholic Archbishop Adewale Martins as it is an oven for baking young and dynamic young students for the future of the Church, the nation and the world at large.

                        The Muslim Community, Main Campus

                        The Muslim Community of the University of Lagos is as old as the University itself. Formally constituted in 1964, when the University was at the temporary site at Idi-Araba. The Community was led by the late Papa B. Daramola and later by Prof. Saburi Biobaku who were among the pioneering members of staff of the University.
                        The membership of the community witnessed significant growth in 1965 when the University moved to its permanent site at Akoka. The Muslims (both University staff and others within the University who were around at that time, usually held their Jumu`ah) congregational prayer on Fridays at the area between the main library and the then dining hall. The need to have a mosque soon became pressing as more Muslim students and staff came to be resident on Campus. The Muslim Community, therefore, put their request for a place to worship before Prof. Saburi Biobaku, the then Vice-Chancellor and a temporary site was allocated to them behind the Department of Mass Communication.
                        The Muslim Community set to work to generate resources to build a temporary structure on the site mentioned above for daily and Jumu`ah Salat. The Community succeeded with the assistance of the University and a temporary mosque was commissioned in 1966.
                        Membership of the Community had grown from 100 in 1964 to over 5,000 today. The weekly Jumu`ah prayer now attract Muslims from far and near. Consequently, in the last fifteen years or so, Jumu`ah prayer have persistently witnessed Fridays in which worshipers defy the scorching sun, or torrential rain to perform their obligatory acts of worship which could last between 60 and 90 minutes on Fridays.
                        The smallness of the size of the temporary mosque coupled with its inability to provide other essential services which a mosque normally provides led the Community to decide to erect a new and befitting mosque for its devotional activities. The Community has since its foundation launched two appeal funds for the mosque-one in 1976 and another in 1981. The proceeds were added to voluntary donations from members (old and young, male and female) for the construction of a new mosque.
                        The University of Lagos Mosque located in the places-of-worship zone on Campus is conceptually and architecturally Islamic. The places-of-worship zone itself is situated to the North West at a distance of about 500 meters from the University Main Gate. Adjacent to the Mosque to the West is the University Chapel to the South is the University  Works and services Complex and to the East is the 2,000-StudentHostel. The Construction work on the Mosque started in May 1981, and was formally commissioned on 13th October, 1985.
                        The mosque covering an area of 4,000 sq. metres (13,123 sq. ft.) itself is a mini-complex consisting of the male and female praying areas, the Mosque Library capable of sitting 100 readers at a time, the Chief Imams Office and a classroom. Its other notable features include (i) the 12 metre-high (39 feet) dome in the centre of the male praying hall, (ii) the minaret which is 25 metres (82 feet) above the ground, (iii) the surrounding packing capable of accommodating 50 cars, and (iv) the courtyards. The male praying area situated on the ground floor can accommodate about 1,000 male worshipers at a time whilst the female praying area on the first floor can accommodate about 500 female worshipers. Consequently, the capacity of the mosque is about 1,500 worshipers at a time.
                        There are two courtyards in the mosque. The inner courtyard measuring 10.5m X 14m with its concrete floor is used as an extension to the prayer hall whenever the need arises. The outer courtyard which is 10.5m x 21m is appropriately landscaped. The space situated to the East together with other praying areas now serve as praying facilities for the two festival prayers, `Idul-Fitr and `Idul-Adhā.
                        Programme of Activities
                        Daily Salāt	The daily salāts are observed in the Mosque as follows:
                        Subh		5:30 am   - 6:10 am
                        Dhuhr		12:55 pm - 1:10 pm
                        `Asr		3:50 pm   - 4:20 pm.
                        Magrib		6:35 pm   - 7:10 pm
                        Ishā’		7:55 pm   - 8:10 pm
                        The timing of the commencement  of various salāts depends on changes in weather.

                        Jumu`ah Salāt – The weekly Jumu`ah Salāt i.e. congregational prayer on Fridays, is observed between 1:00 pm  and 2:00 pm.
                        Post-Salāt Talk:  This is a brief programme of exhortation that focuses on the teachings of Islam as they relate to personal behaviour and functioning within the society.
                        Ramadan Lecture- This annual event is organised on the first Saturday of every Ramadan. Tafsir or Exposition on various themes of the Qur’ān is organised daily during Ramadan. The programme is concluded with Iftar (meal for breaking of fast for limited number of students)
                        Counseling Services - The Mosque has a counseling unit  where professional counselors and the Imams assist students, staff and other members of the public who may require different types of support.
                        Charity: The Mosque receives and distributes Zakāh (Obligatory Charity), Sadaqah (Voluntary Charity) and Waqf (Islamic Endowment) targeting  needy and vulnerable students, staff and members of the public.
                        Visitations
                        The Community organises visitations to correctional centres, orphanages and senior citizens with a vies to offering different types of support.
                        Other Activities- There is an Islamic school organized by the Community.
                        The Muslim Students Society of Nigeria, University of Lagos Branch, has other numerous activities for her members and other members of the Community. The Community also provides other services for both members and the larger Muslim community in Lagos. Such services include marriages, hosting of conferences and other Islamic programmes where people come to drink from the fountain of knowledge.
                        The Community has a multipurpose hall which provides more facilities for marriages conferences and classrooms for the Arabic and Islamic Study school. Other services will be rendered in the hall not only to members of the Community but to the larger community in Lagos.
                        The totality of the services rendered by the University of Lagos Mosque, the salāts and the entire lives of members of the Community are dedicated to the Almighty Allah.
                    </p>
                </article>
                <div className='button-container'>

                    <button onClick={() => navigate('/sectionI/ii')}>Next  - Development and Structure of the University</button>
                </div>

            </div>
        </MainLayout>
    );

}

export default PlacesOfWorship